### PR TITLE
Bump jekyll to v3.8.6

### PR DESCRIPTION
**Pull request by hubot**
**Release**: https://github.com/jekyll/jekyll/releases/tag/v3.8.6
**Diff**: https://github.com/jekyll/jekyll/compare/v3.8.5...v3.8.6

### CODE REVIEW

**Comment by martijnrusschen** [comment]
Let's merge this?

**Comment by sskylar** [comment]
While we are waiting on 4.0 support, any chance we could get this merged in the meantime? 3.8.6 contains a couple bug fixes from 3.8.5 including https://github.com/jekyll/jekyll/issues/7629

**Comment by cmeury** [comment]
Would be great to have this merged, as it contains [a fix](https://github.com/jekyll/jekyll/pull/7679) for a confusing non-actionable error message for remote themes: 

    Invalid theme folder: _sass

**Comment by parkr** [comment]
Fixed via https://github.com/github/pages-gem/pull/689.

**Pull request closed without merging**
