### PR TITLE
Bump jekyll to v3.7.2

### PR DESCRIPTION
**Pull request by hubot**
**Release**: https://github.com/jekyll/jekyll/releases/tag/v3.7.2
**Diff**: https://github.com/jekyll/jekyll/compare/v3.6.2...v3.7.2

### CODE REVIEW

**Comment by jonaschafer** [comment]
👋 Any chance we, avid Jekyll users, could get an ETA on when this update will launch? Currently I'm unable to use collections_dir with Github Pages.

**Comment by johndatserakis** [comment]
Any word on a couple of these pull requests that bump up the Jekyll dependency?

**Comment by aterenin** [comment]
Does anyone have an ETA on when this will go live? I'm still having to generate my sitemap manually because of a bug in Jekyll-sitemap that was fixed months ago.

**Comment by frivoal** [comment]
The number of things that I could do automatically in 3.7.2 that I have to do manually on 3.6.2 is really annoying. Setting up a cheap dedicated host is neither very hard nor very expensive. I hope that github pages can remain sufficiently up to date that this does not become too tempting.

**Pull request merged**
