### PR TITLE
Bump rouge to v3.11.0

### LINKED ISSUE #601: Update Rouge to 3.x
Rouge version 3.x has been released for over a year now, is there any reason for not updating to it?

https://github.com/jneen/rouge/blob/master/CHANGELOG.md#version-300-20170921

### PR DESCRIPTION
**Pull request by pchaigno**
Supersedes #635 and #597.

Fixes #601.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
Suggest rebasing and updating to [rouge v3.11.0](https://github.com/rouge-ruby/rouge/releases/tag/v3.11.0) in order to improve the highlighting in the [Liquid](https://shopify.github.io/liquid/) and [Jekyll](https://jekyllrb.com/docs/) docs.

**Comment by pchaigno** [comment]
@EricFromCanada Done. I received notifications for now Rouge releases, so I won't miss them :-)

**Comment by pchaigno** [comment]
@parkr Did you get a chance to look into this?

**Comment by shopmike** [comment]
👍 LGTM

**Comment by shopmike** [comment]
Closes #635, Closes #597

**Comment by pchaigno** [comment]
@parkr Is something needed to merge this pull request? I noticed there are several other such "Bump xxxxx" pull requests you approved but didn't merge.

**Comment by parkr** [comment]
> Is something needed to merge this pull request?

@pchaigno Yes! There is a bunch of automated internal testing that takes time, and some testing that requires human intervention. We try to wait to merge until we've validated the PR in the wild with Pages builds. No promises on timeline, but I'm hoping we can get this merged 🔜 !

**Comment by pchaigno** [comment]
Okay, thanks for the explanation!

**Pull request merged**
