### PR TITLE
Bump kramdown to v1.12.0

### PR DESCRIPTION
**Pull request by hubot**
**Release**: http://github.com/gettalong/kramdown/releases/tag/REL_1_12_0
**Diff**: http://github.com/gettalong/kramdown/compare/REL_1_11_1...REL_1_12_0
**Changelog**: https://github.com/gettalong/kramdown/blob/master/doc/news/release_1_12_0.page

### CODE REVIEW

**Comment by kunagpal** [comment]
When would this become ready to merge?

**Comment by BeTmAsTeR** [comment]
now the latest version is 1.13.1 https://kramdown.gettalong.org/news.html

**Comment by kunagpal** [comment]
@BeTmAsTeR Nice :+1:

**Comment by parkr** [comment]
Closing in favor of #398.

**Pull request closed without merging**
