### PR TITLE
Bump jekyll to 3.9.2

### PR DESCRIPTION
**Pull request by yoannchaudet**
Addresses https://github.com/github/pages-gem/issues/828

### CODE REVIEW

**Review by YiMysty — APPROVED** [review]

**Review by tjyung — APPROVED** [review]

**Comment by parkr** [comment]
Thanks Yoann!

**Comment by yoannchaudet** [comment]
It's not live everywhere yet but on the launch pad. 🚀

**Comment by parkr** [comment]
Woo! Do I watch actions/Jekyll-pages for updates to what goes live?

**Comment by parkr** [comment]
Ex: https://github.com/actions/jekyll-build-pages/pull/32

**Comment by yoannchaudet** [comment]
Pretty much :)

Even better: https://github.com/actions/jekyll-build-pages/pkgs/container/jekyll-build-pages

We are live! You can see the downloads increasing on the `v1.0.3` container already.

**Comment by parkr** [comment]
That is so cool! Thanks for sharing that :)

**Pull request merged**
