### PR TITLE
Bump rouge to v2.2.1

### PR DESCRIPTION
**Pull request by hubot**
**Release**: https://github.com/jneen/rouge/releases/tag/v2.2.1
**Diff**: https://github.com/jneen/rouge/compare/v1.11.1...v2.2.1

Requires #474 before it may be merged.

### CODE REVIEW

**Comment by chibicode** [comment]
@parkr https://github.com/github/pages-gem/pull/474 is merged, tests should now pass :)

**Comment by parkr** [comment]
@chibicode We have 1 failure due to changing HTML. I'll push up a fix for that, then we have to do some testing internally. 🔜 😄

**Comment by parkr** [comment]
Looks like [Rouge 3.0.0 is out](https://github.com/jneen/rouge/blob/master/CHANGELOG.md)... 🤦‍♂️ Can't keep up with major changes nearly as readily as with minor ones. Looks like a major version bump was due to dropping Ruby 1.9 support, which we already don't support.

We will have to update Jekyll then update Rouge in that order again.

**Comment by JakeWharton** [comment]
If it's API compatible but only has a major version bump due to dropped support, doesn't that mean you could explicitly depend on 3.0.0 with an older version of Jekyll?

**Comment by parkr** [comment]
> If it's API compatible but only has a major version bump due to dropped support, doesn't that mean you could explicitly depend on 3.0.0 with an older version of Jekyll?

It is, in theory, compatible. The issue is that Jekyll itself depends on `rouge < 3` so we can't use Rouge 3.0 with Jekyll 3.6.0. https://rubygems.org/gems/jekyll/versions/3.6.0

I certainly won't hold this PR up, just noting that there's a new version and that it'll be another hoop-jumping exercise to get it out there.

**Comment by JakeWharton** [comment]
Makes sense. Sadly I'm wanting this 2.x bump to fix a specific Kotlin rendering issue and I didn't even realize there was another one.

In any case, thanks for the updates and the forward progress.

**Comment by mattr-** [comment]
We should be able to bump the dependency in Jekyll without a major release.
I’ll look into it later today unless @parkr beats me to it. 😄

**Comment by parkr** [comment]
> We should be able to bump the dependency in Jekyll without a major release.

Absolutely. All I mean to say is that we'll need to update Jekyll before Rouge 3.0 can go out. This will not, however, limit our ability to push Rouge 2 out. Thanks for looking into it @mattr-!

**Comment by mattr-** [comment]
The master branch of jekyll already has support for rouge > 3. We just need to backport it into a stable 3.x release.

**Pull request merged**
