### PR TITLE
Bump rouge to 3.3.0

### PR DESCRIPTION
**Pull request by alexharv074**

### CODE REVIEW

**Comment by DirtyF** [comment]
Duplicate of #597

**Comment by alexharv074** [comment]
Hi @DirtyF , any chance you could help me understand how to run the tests locally and also understand why the tests are failing?

**Comment by cup** [comment]
https://github.com/github/pages-gem/issues/601
https://github.com/github/pages-gem/pull/597

https://github.com/github/pages-gem/pull/635
https://github.com/github/pages-gem/pull/642

**Comment by cup** [comment]
https://github.com/github/jekyll-commonmark-ghpages/pull/5
https://github.com/github/pages-gem/issues/601
https://github.com/github/pages-gem/pull/597

https://github.com/github/pages-gem/pull/635
https://github.com/github/pages-gem/pull/642

**Comment by parkr** [comment]
Fixed by https://github.com/github/pages-gem/pull/652

**Pull request closed without merging**
