### PR TITLE
Add AppVeyor tests for Windows.

### PR DESCRIPTION
**Pull request by XhmikosR**
https://ci.appveyor.com/project/XhmikosR/pages-gem

/CC @parkr

### CODE REVIEW

**Comment by XhmikosR** [comment]
Rebased and updated. Now, only Ruby >= 2.0 fails. I need to figure out how I worked around that locally...

**Comment by benbalter** [comment]
@parkr @Haacked this is out of my league. Any thoughts on AppVayor (windows) tests for the Pages Gem?

**Comment by XhmikosR** [comment]
Actually, locally I simply switch from pygments to rouge to solve this... I'll try a few other things but this is one of the main issues with Ruby >=2 and Jekyll on Windows.

**Comment by XhmikosR** [comment]
@FeodorFitsner: can you please have a look why after `gem update --system` [the build hangs](https://ci.appveyor.com/project/XhmikosR/pages-gem/build/job/wl9c43h6cp0s6uqq)? I have noticed this a long time ago, I was hoping it would have been fixed with newer Ruby versions.

**Comment by parkr** [comment]
It seems to be the best Windows CI system short of running tests on a personal box. The government world will certainly appreciate this.

**Comment by XhmikosR** [comment]
Unfortunately, we hit the known issue with yajl-ruby and Ruby >= 2.0. I can't find any way to work around this at this point.

**Comment by FeodorFitsner** [comment]
Could you please paste a link to specific build/job?

**Comment by XhmikosR** [comment]
@FeodorFitsner: https://ci.appveyor.com/project/XhmikosR/pages-gem/build/job/wl9c43h6cp0s6uqq

Whenever I run `gem update --system` the next command which is `bundle install` is stuck.

**Comment by FeodorFitsner** [comment]
Which version of Ruby is that?

**Comment by XhmikosR** [comment]
2.0 but should happen with 1.9.3 too.

**Comment by FeodorFitsner** [comment]
Apparently, it doesn't hang, but installs gem very slow. On Hyper-V it took less than 2 minutes.
1.9.3: https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.117
2.0.0: https://ci.appveyor.com/project/FeodorFitsner/simple-console/build/1.0.116

On Azure I cancelled both builds after 20 minutes. Such a huge difference lead me to a thought it might be I/O is the bottleneck (Hyper-V workers have SSD drives). I'm going to have another build to see interactively what's going on.

**Comment by XhmikosR** [comment]
The last time I tried this the build was cancelled due to timeout.
Something like 20 or 25 minutes. So I was never able to see it succeed.

**Comment by FeodorFitsner** [comment]
This is how it looks like with `--debug` enabled: https://ci.appveyor.com/project/appvyr/simple-console/build/1.0.62

**Comment by XhmikosR** [comment]
Yeah, I see those in my dev machine too with Ruby 2.1.5. But it installs in like 3 seconds there.

**Comment by FeodorFitsner** [comment]
OK, could you help me to outline the draft then? We could switch to our forums if you like.

I see the following:
1) Switching Ruby version (from already installed on build workers)?
2) Setting up certificates bundle
3) DNS issue on Azure environment

What else?

**Comment by XhmikosR** [comment]
I'd say those 3 are the main issues I've come across with Ruby CI testing so far. Link for the forums?

**Comment by FeodorFitsner** [comment]
Yeah, makes sense. Thanks!

**Comment by benbalter** [comment]
@XhmikosR how'd you get around the Yajl-ruby issue? Could you document here for others? Had trouble understanding the current state of the pull request with the AppVeyor feedback mixed in.

**Comment by XhmikosR** [comment]
@benbalter: I didn't as you can see from the above build; 1.9.3 worked and works fine with the current 0.6.0 pygments.rb gem, >=2.0 have the issue. [Pending](https://github.com/tmm1/pygments.rb/pull/106#issuecomment-69540289) to see if a new pygments.rb gem with newer yajl-ruby will fix the issue...

Personally, I just use rouge and be done with it. It works the same and even better; for example, YAML highlighting works fine with rouge.

**Comment by XhmikosR** [comment]
@benbalter: can you add an AppVeyor account, and rename it to pages-gem or something like I say [here](https://github.com/jekyll/jekyll/pull/3115#issue-48958641)?

**Comment by XhmikosR** [comment]
Also, @benbalter, we need someone to add AppVeyor properly with the hook and all for this repo.

**Comment by XhmikosR** [comment]
(Just mentioning it here too)

After #117 is merged, all tests [will pass](https://ci.appveyor.com/project/XhmikosR/pages-gem/build/41) on Windows!

So I need @benbalter to do a couple of changes so that we have a working badge and this should be ready to merge.

Also, note that the builds won't take so long to complete due to caching which is in effect after a successful build.

**Comment by XhmikosR** [comment]
https://ci.appveyor.com/project/XhmikosR/pages-gem/build/43
https://ci.appveyor.com/project/XhmikosR/pages-gem/build/46

So, with caching in effect, the whole build is faster but still uber slow IMO.

We could skip some Ruby versions to speed things up though. I'll wait for feedback about this.

**Comment by XhmikosR** [comment]
@benbalter: Updated. Added Ruby 2.2 too.

Please check my previous messages here too.

**Comment by XhmikosR** [comment]
Updated one more time...

**Pull request closed without merging**
