### PR TITLE
Windows tests

### PR DESCRIPTION
**Pull request by benbalter**
Inspired by https://github.com/github/pages-gem/pull/103, this was a pass at spiking out a minimal windows test to ensure we don't break things going forward.

[Tests pass](https://ci.appveyor.com/project/benbalter/pages-gem), but it requires a bit of monkey patching to get around a [yajl-ruby compatability issue](https://github.com/brianmario/yajl-ruby/issues/116), which I will file upstream.

### CODE REVIEW

**Comment by parkr** [comment]
Nice! :+1: 

Adding the AppVeyor hook to this repo will help tremendously.

**Comment by XhmikosR** [comment]
I don't see why you don't cherry pick my PR and do your changes on top of it.

**Comment by benbalter** [comment]
(hold for the time being is a permission issue with AppVeyor being able to set this repos commit status).

@XhmikosR Thanks again for #103. There was a lot going on there, and being my first time using AppVeyor (or any windows CI), was hoping to learn how to :fish: myself! :smile:

**Comment by XhmikosR** [comment]
@benbalter: I strongly believe you shouldn't go ahead with this PR like this. If you use my branch and make changes on top of it, that would be the best IMO.

My patch fully supports what the Jekyll version that's currently included in pages-gem supports: >= 1.9.3. Also, it's tested that it works https://ci.appveyor.com/project/XhmikosR/pages-gem/build/38 >=2.0 issue is a pygments-rb one which I hope we'll finally get fixed with a new gem version.

**Pull request closed without merging**
