### PR TITLE
Bump jekyll-feed to v0.11.0

### PR DESCRIPTION
**Pull request by hubot**
**Release**: https://github.com/jekyll/jekyll-feed/releases/tag/v0.11.0
**Diff**: https://github.com/jekyll/jekyll-feed/compare/v0.10.0...v0.11.0

### CODE REVIEW

**Comment by mortenson** [comment]
I'm excited for this to get in! With the update users will be able to generate feeds per category and collection which is a feature I've been looking forward to.

**Comment by parkr** [comment]
Merged in https://github.com/github/pages-gem/pull/591

**Comment by mortenson** [comment]
@parkr Sorry to bother you, but do you know when this change will go live on Github Pages? I see the old jekyll-feed version at https://pages.github.com/versions/. Thanks!

**Comment by DirtyF** [comment]
@mortenson Have you tried? It was released in https://github.com/github/pages-gem/releases/tag/v193

**Comment by parkr** [comment]
Updated the website!

**Comment by mortenson** [comment]
@DirtyF It turns out that the whole time I've been using Github Pages, I've never used the actual pages-gem in my Gemfile. I started using it and I can see my per-category feeds. Thank you!

**Pull request closed without merging**
