### PR TITLE
warn about bundler issue in README

### PR DESCRIPTION
**Pull request by jldec**
Trying to help users avoid #351 
(caused by https://github.com/bundler/bundler/issues/5154)

ready for 👀

### CODE REVIEW

**Comment by jldec** [comment]
Remember to remove the warning and the version number from the README when Bundler releases a fix.

**Comment by benbalter** [comment]
@parkr @jldec I think it's a mistake to tell users to lock the gem at version `104` as many users will fix the problem once and move on, forgetting about the flag. Can we update the instructions to be `>= 104` and achieve the same result?

**Comment by jimkohl** [comment]
Ben
I first attempted as you suggest but that didn't work.  Using the specific version only worked.  

While I generally share your concern in this case many of us are well aware of this issue and awaiting the resolution to resolve correctly.  Spent too much time helping others Monday get around this. 
Tx for all you do here!
Jim

**Comment by parkr** [comment]
@benbalter `>= 104` and `104` have the same effect: install v104. Sadly, `>= 104` doesn't work presently. That said, it's a better place to be once bundler *is* fixed.

**Comment by benbalter** [comment]
What if we add `jekyll ~> 3.3` to force the higher resolution?

**Pull request merged**
