### PR TITLE
Bump jekyll to v3.4.5

### PR DESCRIPTION
**Pull request by hubot**
**Release**: https://github.com/jekyll/jekyll/releases/tag/v3.4.4
**Release**: https://github.com/jekyll/jekyll/releases/tag/v3.4.4
**Diff**: https://github.com/jekyll/jekyll/compare/v3.4.3...v3.4.5

### CODE REVIEW

**Comment by parkr** [comment]
We may need to bump some plugins here as well.

**Comment by parkr** [comment]
@benbalter it works!

**Comment by jeaye** [comment]
What's this blocked on?

**Comment by pathawks** [comment]
@jeaye Any update to GitHub Pages requires a full review from the GitHub Security team. It just takes time. :beers:

**Comment by jeaye** [comment]
Makes sense to me. Cheers.

**Comment by parkr** [comment]
v3.4.4 had a bug. We'll give v3.4.5 a shot next.

**Pull request merged**
