### PR TITLE
Bump jekyll to v3.5.1

### PR DESCRIPTION
**Pull request by hubot**
**Release**: https://github.com/mojombo/jekyll/releases/tag/v3.5.1
**Diff**: https://github.com/mojombo/jekyll/compare/v3.4.3...v3.5.1

### Blockers

- [x] [Jekyll Gist]( jekyll/jekyll-gist#41)
- [x] [Jekyll redirect from compatibility](https://github.com/jekyll/jekyll-redirect-from/pull/157)
- [x] [Jekyll sitemap compatibility](https://github.com/jekyll/jekyll-sitemap/issues/176)

### CODE REVIEW

**Comment by jekylltools** [comment]
These seem to be failing because of liquid: `Bundler could not find compatible versions for gem "liquid":`

**Comment by DirtyF** [comment]
@benbalter you might want to add Jekyll Gist compatibility:  https://github.com/jekyll/jekyll-gist/pull/41

**Comment by benbalter** [comment]
All the above plugins now work on 3.5, based on my testing, and with https://github.com/jekyll/jekyll-redirect-from/pull/160, tests will pass for redirect-from as well.

**Comment by parkr** [comment]
@benbalter You mentioned in our ☎️  yesterday that this wasn't working with `plugins` or something like that. Can you show me a failing CI or paste a reproduction step in here? I'd be happy to prioritize this next week.

**Comment by benbalter** [comment]
@parkr see the internal PR cross referenced above.

**Comment by sethjackson** [comment]
Any chance this is getting merged soon?

**Comment by gmile** [comment]
BTW Jekyll bot points to mojombo/jekyll, while it should be jekyll/jekyll?

**Pull request merged**
