### PR TITLE
Bump pygments to 0.6.1

### PR DESCRIPTION
**Pull request by gjtorikian**
Closes https://github.com/github/pages-gem/issues/116.

/cc @XhmikosR @parkr @benbalter

### CODE REVIEW

**Comment by XhmikosR** [comment]
LGTM thanks! Will you also publish a new gem if everything goes well?

**Comment by gjtorikian** [comment]
Yep.

**Comment by XhmikosR** [comment]
Awesome, I'll try again after the gem is out.

**Comment by XhmikosR** [comment]
@gjtorikian: I couldn't wait to try this and [it works fine](https://ci.appveyor.com/project/XhmikosR/pages-gem/build/41) :D

I can't stretch enough how important this change is for Windows users; it basically makes Jekyll work again with Ruby >= 2.x.

Thanks @tmm1 for https://github.com/tmm1/pygments.rb/pull/106 and the new gem!

PS. About #103, I strongly believe @benbalter shouldn't go ahead with his PR. My PR is complete, and it's only fair to merge that.

**Comment by parkr** [comment]
:heart:

**Pull request merged**
