### PR TITLE
Update rouge to v3.18.0

### PR DESCRIPTION
**Pull request by axic**
This brings in fixes to C++, Python, Java, Lua, Rust, Ruby, Scala, Kotlin, PHP, Pascal, TypeScript, CoffeeScript, TOML, Markdown and introduces support (not a comprehensive list) for Varnish, GHC, Objective-C++,  Rego and Solidity.

It would be nice to have these applied to projects using pages. Please let me know if there is a way to override the `rouge` dependency in a project using github-pages.

### CODE REVIEW

**Comment by axic** [comment]
I think the CI failure is not caused by this change, but I can try to fix it:
```
Running Ruby style tests...
vendor/bundle/ruby/2.3.0/gems/rubocop-github-0.14.0/config/_default_shared.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: The `Lint/EndInMethod` cop has been renamed to `Style/EndBlock`.
(obsolete configuration found in vendor/bundle/ruby/2.3.0/gems/rubocop-github-0.14.0/config/_default_shared.yml, please update it)
The command "script/cibuild" exited with 2.
```

**Comment by axic** [comment]
@parkr is there any chance to get this considered for a new github-pages release?

**Comment by parkr** [comment]
Done in #690.

**Comment by axic** [comment]
@parkr thanks, this is great! (Would have been nice to get this merged first though, haha :wink:)

**Pull request closed without merging**
