### PR TITLE
Update minima to 2.3.0

### PR DESCRIPTION
**Pull request by matteeyah**
Closes https://github.com/github/pages-gem/issues/520

### CODE REVIEW

**Comment by matteeyah** [comment]
cc @malreynolds

**Comment by malreynolds** [comment]
Since this still hasn't been merged in and the minima guys seem to be on a roll: [2.3.0](https://github.com/jekyll/minima/releases/tag/v2.3.0) is out, so we might as well bump it up again :-)

**Comment by matteeyah** [comment]
@malreynolds Done! Thanks.

**Comment by malreynolds** [comment]
@benbalter @parkr can we get this merged in? Thanks!

**Comment by sethjackson** [comment]
Any chance this gets merged soon?

**Comment by chibby0ne** [comment]
I was about to open an issue for this same thing as well. https://github.com/github/pages-gem/issues/520 is still open. Can we close that one and merge this?

**Comment by DirtyF** [comment]
Duplicate of #539

**Pull request merged**
