### PR TITLE
Bump rouge to v3.3.0

### PR DESCRIPTION
**Pull request by hubot**
**Release**: https://github.com/jneen/rouge/releases/tag/v3.3.0
**Diff**: https://github.com/jneen/rouge/compare/v2.2.1...v3.3.0

### CODE REVIEW

**Comment by snh** [comment]
Requires https://github.com/github/jekyll-commonmark-ghpages/pull/5.

**Comment by snh** [comment]
I believe this requires https://github.com/github/jekyll-commonmark-ghpages/pull/5.

**Comment by nbering** [comment]
I went looking for a way to get the `hcl`/`terraform` language working on github-pages, and found my way here. I'm not sure what the blocker is here, but I wonder if it's unrelated to the change in the PR.

The build error is:
```
Bundler could not find compatible versions for gem "activesupport":
```

But the Rouge package does not declare a dependency on `activesupport`. Or any other gem for that matter.

https://rubygems.org/gems/rouge/versions/3.3.0

Is there anything the community can do to help unblock this?

**Comment by cup** [comment]
https://github.com/github/pages-gem/issues/601

https://github.com/github/pages-gem/pull/597
https://github.com/github/pages-gem/pull/635
https://github.com/github/pages-gem/pull/642

**Comment by cup** [comment]
https://github.com/github/jekyll-commonmark-ghpages/pull/5
https://github.com/github/pages-gem/issues/601

https://github.com/github/pages-gem/pull/597
https://github.com/github/pages-gem/pull/635
https://github.com/github/pages-gem/pull/642

**Comment by cup** [comment]
@parkr @snh can we please get this merged?
https://github.com/github/jekyll-commonmark-ghpages/pull/5 was merged in
January, and the current version of Rouge:

https://github.com/github/pages-gem/blob/9fd34b8e6d0dc070e19fdfe1d9c7c44930461b46/lib/github-pages/dependencies.rb#L19

is 2 years old now:

https://github.com/rouge-ruby/rouge/releases/tag/v2.2.1

with some important issues being fixed since then:

https://github.com/rouge-ruby/rouge/pull/1165

**Comment by JohannesLichtenberger** [comment]
Yes please, I really really need XQuery syntax highlighting.

**Comment by parkr** [comment]
Fixed by https://github.com/github/pages-gem/pull/652

**Pull request closed without merging**
