### PR TITLE
Bump jekyll-titles-from-headings to v0.1.4

### PR DESCRIPTION
**Pull request by hubot**
**Release**: https://github.com/benbalter/titles-from-headings/releases/tag/v0.1.4
**Diff**: https://github.com/benbalter/titles-from-headings/compare/v0.1.3...v0.1.4

### CODE REVIEW

**Comment by benbalter** [comment]
Wrong gem name (missing `jekyll-` prefix). Closing and will re-open.

**Comment by benbalter** [comment]
Just kidding. Gem name is right, metadata is wrong, hence the wrong link. Will get a redirect in there for now, and will update the Gem metadata.

**Comment by benbalter** [comment]
@parkr any thoughts on how best to retain Ruby 2.0 support? Lock Nokogiri to `~> 1.6.0`? Is it enough to do it in the Gemfile or does it have to be in the Gemspec?

**Comment by parkr** [comment]
@benbalter How important is Ruby 2.0 support to you? It was [EOL'd (including security patches) last February 24](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/). It's been nearly a year since it's been decommissioned – maybe we start requiring 2.1.

**Comment by benbalter** [comment]
> How important is Ruby 2.0 support to you?

I'll defer to you here.

**Comment by parkr** [comment]
> > How important is Ruby 2.0 support to you?
>
> I'll defer to you here.

The only reason to keep it is that it's the default Ruby version for macOS X.

```
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
```

I know a bunch of people use that installation – think it's worth the effort? Nokogiri doesn't need to be updated, right? It seems like it was stable beforehand.

**Comment by benbalter** [comment]
> it's the default Ruby version for macOS X.

That sounds like a strong reason to maintain 2.x support.

**Comment by parkr** [comment]
> That sounds like a strong reason to maintain 2.x support.

Agreed. In that case, if you have a second, add nokogiri to the list of dependencies and lock it to the latest version with Ruby 2.0 support.

**Pull request merged**
